# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
registries:
  boot-cluster-conditionals : # Gir tilgang til registre innad i nav med boot-cluster-conditionals som inngang (PATen bestemmer)
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/boot-cluster-conditionals
    username: x-access-token
    password: ${{ secrets.PAT }}

updates:
  - package-ecosystem: github-actions
      directory: "/"
      registries:
        - boot-cluster-conditionals
      schedule:
        interval: daily
      open-pull-requests-limit: 20
