version: 2
registries:
  maven-github :
    type: "maven-repository"
    url: https://maven.pkg.github.com/navikt/aap-domain
    username: x-access-token
    password: ${{ secrets.GITHUB_TOKEN }}

updates:
 - package-ecosystem: "maven"
    directory: "/"
    registries:
      - maven-github
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 10
 - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "hourly"
    open-pull-requests-limit: 10
