version: 2
registries:
  boot-cluster-conditionals : # Gir tilgang til registre innad i nav med boot-cluster-conditionals som inngang (PATen bestemmer)
    type: maven-repository
    url: https://maven.pkg.github.com/navikt/boot-cluster-conditionals
    username: x-access-token
    password: ${{ secrets.GITHUB_TOKEN }}

updates:
  - package-ecosystem: github-actions
      directory: "/"
      registries:
        - boot-cluster-conditionals
      schedule:
        interval: daily
      open-pull-requests-limit: 20
