management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
      health:
        show-details : always
no.nav:
  security:
    jwt:
      client:
        registration:
          aap-fss-proxy:
            token-exchange:
              audience: dev-fss:aap:aap-fss-proxy
mvc:
  log-request-details : true
joark:
  base-uri: https://aap-fss-proxy.dev-fss-pub.nais.io/joark