spring:
  application:
    name: "aap-soknad-konsument"
  main:
    banner-mode: off
  jackson:
    default-property-inclusion: always
    mapper:
      accept-case-insensitive-enums: true
      accept-case-insensitive-properties: true
    deserialization:
      read-unknown-enum-values-using-default-value: true
      accept-single-value-as-array: true
      fail-on-unknown-properties: true
    serialization:
      write-empty-json-arrays: true
      fail-on-empty-beans: false
management :
  info:
    java:
      enabled: true
    env:
      enabled: true
  health:
    ping:
      enabled: false
    diskspace:
      enabled: false
springdoc:
  packagesToScan: no.nav.aap
  swagger-ui:
    disable-swagger-default-url: true