management :
  endpoints:
    web:
      exposure:
        include:  '*'
  endpoint:
      health:
        show-details : always
mvc:
  log-request-details : true
joark:
  base-uri: https://aap-fss-proxy.dev-fss-pub.nais.io